AllCops:
  Include:
    - 'lib/*'
    - 'helpers/*'
  Exclude:
    - 'spec/*'
    - 'Gemfile'

Documentation:
  Enabled: false

LineLength:
  Max: 136

MethodLength:
  Max: 12

ClassLength:
  Max: 105

AccessorMethodName:
   Enabled: false

CaseEquality:
   Enabled: false

AbcSize:
  Max: 19